DROP TABLE IF EXISTS images;

CREATE TABLE images (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "created_at" NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "filename" TEXT NOT NULL,
    "path" TEXT NOT NULL,
    "description" TEXT NOT NULL
);